# Prettier friendly markdownlint config (all formatting rules disabled)
extends: markdownlint/style/prettier
code-block-style:
  style: fenced
first-line-h1: false
no-duplicate-heading:
  siblings_only: true
no-inline-html: false
no-trailing-punctuation: false
no-space-in-emphasis: false # Required to allow comments in MDX files
